name: Autism
description: BYU CS Autism server autism.
version: 0.0.1
main: edu.byu.cs.autism.Autism
commands:
  spawn:
    description: Return to the global spawn point.
  maze:
    description: Create a maze in the main world.
  prompt:
    description: Display a random prompt question.
  wonGame:
    description: Records that two players won a game and provides their reward
