name: Autism
description: BYU CS Autism server autism.
version: 0.0.1
main: edu.byu.cs.autism.Autism
commands:
  spawn:
    description: Return to the global spawn point.
  prompt:
    description: Display a random prompt question.
